### PR TITLE
R&Y: Updated Arcade Data Card section in arcadecards.md

### PR DESCRIPTION
**Pull request by ry4000**
Made several updates to the Arcade Data Card section to reflect updated knowledge on what the Flipper Zero is capable of emulating.

Many thanks in advance, and kind regards,

-Randy.

### CODE REVIEW

**Comment by ase1590** [comment]
I might suggest that the Arcade Data Card Eumuation notes section get reformatted slightly. 
I think we can move to using bullet points and numbers for these items, perhaps something like this?

```
- Emulation compatibility cannot be tested for Taito games without assistance from Members located within Japan.
- The `AM.PASS` and `e-amusement pass` ISO15693 cards are not compatible with each others' games.
- If FeliCa emulation does not work, you may need to:
    1. Back up your microSD card;
    1. Synchronise your Flipper Zero with your Mobile App;
    1. Factory reset your Flipper Zero;
    1. Format your microSD card; then,
    1. Update to the latest OFW Version.
- There is an issue that prevents the Flipper Zero from emulating FeliCa Amusement IC Cards on Sega games.
- There is an issue that prevents the Flipper Zero from emulating ISO15693 e-amusement passes on Konami games.
```

`Compatability` also looks to be a typo of `Compatibility` I think

Other than that, looks good :+1:

**Comment by ry4000** [comment]
Changes recommended were made and further simplified, with many thanks.

Compatibility table updated to clarify that the Flipper Zero cannot emulate more credentials on Sega games.

**Comment by ase1590** [comment]
The current format you have for the Arcade Data Card Emulation Compatibility Notes get converted into a code block with the current style. Is this what you intend? Otherwise if not, you might wish to implement my suggested style from earlier
Here's how it looks currently:
image

**Comment by ry4000** [comment]
It was intended, though have since changed it to the preferred style. I am unsure how to revert the roman numerals back to numbers, though, so will leave that at your discretion.

**Comment by ase1590** [comment]
Thank you!
Merging

**Pull request merged**
